export const symptomOptions = [
  { value: "adiccion", label: "Adicción" },
  { value: "agorafobia", label: "Agorafobia"},
  { value: "anorexia", label: "Anorexia"},
  { value: "ans_social", label: "Ansiedad social"},
  { value: "ansiedad", label: "Ansiedad" },
  { value: "autismo", label: "Autismo"},
  { value: "autoestima", label: "Autoestima" },
  { value: "bipolar", label: "Bipolaridad" },
  { value: "bulimia", label: "Bulimia"},
  { value: "depresion", label: "Depresión" },
  { value: "esquizofrenia", label: "Esquizofrenia" },
  { value: "estres", label: "Estrés" },
  { value: "ptsd", label: "Estrés post-traumático"},
  { value: "fobias", label: "Fobias"},
  { value: "genero", label: "Identidad de género" },
  { value: "insomnia", label: "Insomnia" },
  { value: "paranoia", label: "Paranoia"},
  { value: "pareja", label: "Problemas de pareja" },
  { value: "sexualidad", label: "Sexualidad" },
  { value: "terror", label: "Terrores nocturnos"},
  { value: "antisocial", label: "Trastorno antisocial"},
  { value: "atencion", label: "Trastorno de déficit de atención e hiperactividad"},
  { value: "despersonalizacion", label: "Trastorno de despersonalización"},
  { value: "multiple", label: "Trastorno de identidad disociativo o múltiples personalidades"},
  { value: "panico", label: "Trastorno de pánico"},
  { value: "bordeline", label: "Trastorno límite de la personalidad" },
  { value: "ocd", label: "Trastorno obsesivo-compulsivo"},
  { value: "atracon", label: "Trastorno por atracón"},
  { value: "trauma", label: "Trauma"},

];
